---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    run: bar-app
  name: bar-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: bar-app
  template:
    metadata:
      labels:
        run: bar-app
    spec:
      containers:
      - name: bar-app
        image: mgreenly/bar-app:v0.1.0
        ports:
        - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    run: bar-app
  name: bar-app
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "leastconn"
spec:
  selector:
    run: bar-app
  ports:
  - name: port-2
    port: 80
    protocol: TCP
    targetPort: 8088
