---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
spec:
  rules:
  - host: logic-refinery.io
    http:
      paths:
      - path: /foo
        backend:
          serviceName: foo-app
          servicePort: 80
      - path: /bar
        backend:
          serviceName: bar-app
          servicePort: 80
